name: Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:

  validar_codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Validar arquivos do projeto
        run: |
          echo "Verificando se o arquivo index.html existe..."
          if [ ! -f index.html ]; then
            echo "Erro: arquivo index.html não encontrado!"
            exit 1
          fi
          echo "Arquivo encontrado. Validação OK."

  simular_build:
    needs: validar_codigo
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Simular build
        run: |
          echo "Iniciando processo de build..."
          echo "Build realizado com sucesso."

      - name: Mostrar mensagem secreta
        run: |
          echo "Mensagem secreta:"
          echo "${{ secrets.MENSAGEM_SECRETA }}"
